Initial Commit
im-open/iis-site-action pull request #1
Opened 2021-08-16 16:06 UTC by hpractv

A GitHub action that can start, stop, or restart an On-Prem IIS website

2021-08-18 13:02 UTC, danielle-casella-adams requested changes
I think the title for this PR is not the right one.  Also have you been able to test it out?

2021-08-18 13:02 UTC, danielle-casella-adams commented on README.md
> +The IIS action uses Web Services for Management, [WSMan], and Windows Remote Management, [WinRM], to create remote administrative sessions. Because of this, Windows OS GitHubs Actions Runners, `runs-
```suggestion
The IIS action uses Web Services for Management, [WSMan], and Windows Remote Management, [WinRM], to create remote administrative sessions. Because of this, Windows Actions Runners, `runs-on: [windows-2019]`, must be used. If the IIS server target is on a local network that is not publicly available, then specialized self-hosted runners, `runs-on: [self-hosted, windows-2019]`,  will need to be used to broker commands to the server.
```

2021-08-18 13:02 UTC, danielle-casella-adams commented on README.md
> +  restart-app-pool:
```suggestion
  restart-iis-site:
```

2021-08-18 13:02 UTC, danielle-casella-adams commented on README.md
> +      uses: 'im-open/app-pool-action@v1.0.0'
```suggestion
      uses: 'im-open/iis-site-action@v1.0.0'
```

2021-08-18 13:02 UTC, danielle-casella-adams commented on README.md
> +| `website_name`             | true        | The name of the website to perform action on          |
The action.yml has this with '-' not '_'
```suggestion
| `website-name`             | true        | The name of the website to perform action on          |
```

2021-08-18 13:02 UTC, danielle-casella-adams commented on README.md
> +        server-public-key: ${{ env.cert-path }}
It looks like you're missing the website-name argument here.

2021-08-18 13:02 UTC, danielle-casella-adams commented on action.yml
> +name: 'App Pool Action'
```suggestion
name: 'IIS Site Action'
```

2021-08-18 13:02 UTC, danielle-casella-adams commented on iis_action.ps1
> +    [ValidateSet( 'start', 'stop', 'restart')]
Is this case sensitive?  It's probably worth a note on the readme because your script assumes it's lowercase.

2021-08-27 14:06 UTC, JosephDSchwartz commented on README.md
> +[PowerShell Remoting over HTTPS with a self-signed SSL certificate]: https://4sysops.com/archives/powershell-remoting-over-https-with-a-self-signed-ssl-certificate
(*Bernie Sanders meme*) I am once again asking you about this link

2021-08-30 17:09 UTC, danielle-casella-adams approved these changes, later dismissed

2021-09-01 14:13 UTC, hpractv commented on README.md
> +        server-public-key: ${{ env.cert-path }}
I'll get it added.

2021-09-01 14:13 UTC, hpractv commented on iis_action.ps1
> +    [ValidateSet( 'start', 'stop', 'restart')]
I'll force the input to be lower case.

2021-09-01 14:13 UTC, hpractv commented on README.md
> +[PowerShell Remoting over HTTPS with a self-signed SSL certificate]: https://4sysops.com/archives/powershell-remoting-over-https-with-a-self-signed-ssl-certificate
I'll add the link back in, because it gives a lot more detail than I can in this README.

2021-09-07 14:02 UTC, danielle-casella-adams approved these changes

2021-09-08 15:02 UTC, merged