Bug Fix: Complex Password Quote
im-open/iis-site-action pull request #5
Opened 2022-05-26 14:53 UTC by hpractv

# Summary of PR changes

- Changed the quotes to handle to fix bug with generated complex passwords

## PR Requirements
- [ ] For JavaScript actions, the action has been recompiled.  
  - See the *Recompiling* section of the repository's README.md for more details.
  - This does not apply to Composite Run Steps actions unless a package.json is present and contains a build script.
- [ ] For major, minor, or breaking changes, at least one of the commit messages contains the appropriate `+semver:` keywords.
  - See the *Incrementing the Version* section of the repository's README.md for more details.
- [ ] The examples in the repository's `README.md` have been updated with the new version.  
  - See the *Incrementing the Version* section of the repository's README.md for more details on how the version will be incremented.
- [ ] The action code does not contain sensitive information.

2022-05-26 15:34 UTC, JosephDSchwartz submitted a review, later dismissed

2022-05-26 22:14 UTC, mike-schenk requested changes
single quotes included in password will still break this.

2022-05-27 14:08 UTC, hpractv commented
> single quotes included in password will still break this.
> 
> See [im-open/register-windows-service#5](https://github.com/im-open/register-windows-service/pull/5) for an alternative.

The latest push fixes this with `@'` encapsulation of the secure string.

2022-05-27 17:23 UTC, mike-schenk approved these changes

2022-05-27 18:26 UTC, merged